### ISSUE TITLE
non-ascii XML output does not work with Python2

### ISSUE THREAD

**Issue by goodmami** [delph-in/pydelphin#106]
Converting to an XML-based format (e.g. `mrx` or `dmrx`) with Python2 generates a UnicodeDecodeError when there is non-ascii characters in the stream:

```
  [...]
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1073, in _escape_cdata
    return text.encode(encoding, "xmlcharrefreplace")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe3 in position 2: ordinal not in range(128)
```

**Comment by goodmami** [comment]
Here is a simple MRS that illustrates the problem:

```
[ TOP: h0
  INDEX: e2 [ e TENSE: pres MOOD: indicative PROG: - PERF: - ASPECT: default_aspect PASS: - SF: prop ]
  RELS: < [ "_スマート_a_1_rel"<0:4> LBL: h1 ARG0: e2 ARG1: i3 ] >
  HCONS: < h0 qeq h1 > ]
```

One #164 is fixed, you'll see an error like the one in the original post. The first trace in PyDelphin code, though, is this:

```
  File "delphin/mrs/util.py", line 94, in etree_tostring
    return etree.tostring(elem, encoding='utf-8', **kwargs).decode('utf-8')
```

So it seems the `delphin.mrs.util.etree_tostring()` function is probably where to look for a fix.

**Comment by mcmillanmajora** [comment]
You're right. It only solves the delphin command. I tried applying the conversion in loads() instead, and it works for the command line, but the encoding issue persists when using the API.

**Comment by goodmami** [comment]
Here's a unit test (I called it `tests/mrs_util_test.py`) that passes with Python3 but fails with Python2:

```python
# -*- coding: utf-8 -*-

from delphin.mrs.util import etree_tostring

def test_etree_tostring():
    import xml.etree.ElementTree as etree
    e = etree.Element('a')
    e.text = 'a'
    assert etree_tostring(e, encoding='unicode') == u'<a>a</a>'
    e.text = u'あ'
    assert etree_tostring(e, encoding='unicode') == u'<a>あ</a>'
    e.text = 'あ'
    assert etree_tostring(e, encoding='unicode') == u'<a>あ</a>'
```
